CREATE TABLE Activities (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR(MAX) NOT NULL,
    IsPrivate BIT NOT NULL
);

CREATE TABLE ActivityContents (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    ActivityId UNIQUEIDENTIFIER NOT NULL,
    ContentId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (ActivityId) REFERENCES Activities(Id) ON DELETE CASCADE
);
